# Generated by Django 4.2 on 2023-04-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.FileField(upload_to='')),
                ('price', models.PositiveIntegerField()),
                ('details', models.JSONField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
